pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:realtyna/realtyna-mvc-core.git
          - cd realtyna-mvc-core.git
          - git push --mirror git@github.com:realtynapublic/Realtyna-MVC-Core.git